# Homebrew info

APP_TITLE       :=  Luma3DS Updater
APP_DESCRIPTION :=  Updater for Luma3DS releases
APP_AUTHOR      :=  Hamcha

GIT_VER := $(shell git describe --dirty --always --tags)

# Directories

BINDIR      :=  out
BUILD		:=	build
SOURCES		:=	source source/7z source/minizip
DATA		:=	data
INCLUDES	:=	include
#ROMFS		:=	romfs