# Homebrew info

APP_TITLE       := Luma3DS Updater
APP_DESCRIPTION := Updater for Luma3DS releases
APP_AUTHOR      := Hamcha

ICON            := meta/icon.png

# CIA info

PRODUCT_CODE := CTR-L-UPDR
UNIQUE_ID    := 0x1dea

BANNER_AUDIO := meta/jingle.wav
BANNER_IMAGE := meta/luma.cgfx

# Directories

BINNAME := lumaupdater
BINDIR  := out
BUILD   := build
SOURCES := source source/7z source/minizip source/md5
DATA    := data

# Build info

LIBRARIES := ctru m z

### HB-specific makefile code ###

# Use fallbacks and mocks to compile a version that works on Citra if wanted
ifdef CITRA
	EXTRACFLAGS := -DFAKEDL
endif

# Expose UNIQUE_ID (with padding) to updater for CIA detection
EXTRACFLAGS += -DUNIQUE_ID=$(UNIQUE_ID)00
